version: "3.8"

services:
  app:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: on-failure
    command: >
      sh -c "npm start"

  db:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
        - ./postgres:/var/lib/postgresql/data
    restart: on-failure

  web:
    image: nginx:alpine
    ports:
      - "80:80"
    restart: on-failure
    volumes:
      - ./client:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
